version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 397745288445.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - docker build --platform linux/amd64 -t mathesh-manual-ror-repo .
      - docker tag mathesh-manual-ror-repo:latest 397745288445.dkr.ecr.ap-south-1.amazonaws.com/mathesh-manual-ror-repo:latest

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push 397745288445.dkr.ecr.ap-south-1.amazonaws.com/mathesh-manual-ror-repo:latest
      - printf '[{"name":"rails-container","imageUri":"397745288445.dkr.ecr.ap-south-1.amazonaws.com/mathesh-manual-ror-repo:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
